name: 'openweathermap_dbt'
config-version: 2
version: '1.0.0'

profile: 'openweathermap_dbt_profile'

model-paths: ["models"]
test-paths: ["tests"]

models:
  openweathermap_dbt:
    +materialized: table
    +database: meteomatic
    +schema: openweathermap